ami = "ami-006dcf34c09e50022"
region1 = "us-east-1"
ec2name = "ec2-project"
s3name = "eeman-s3-project"
dynamodb_table_name = "eeman-table"
availability_zone_a = "us-east-1a"
availability_zone_b = "us-east-1b"
